config/routes.rb
Rails.application.routes.draw do
 

  #user routes
  get  "/signup", to: "users#new"
  get "profile", to: "users#show"
  resources :users, only: [:create]

  #sessions routes
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"
  resources :sessions, only: [:create]

  #blog routes
  resources :blogs, except: [:index]

  root "blogs#index"

end

app/models/blog.rb
class Blog < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :blog, dependent: :destroy
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def current_user
	@current_user ||= User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user

def authorize
	unless current_user
		redirect_to login_path
	end
end


end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_filter :authorize, except: [:index, :show]
  #show all the blogs in db
  def index
    @blogs = Blog.all
    render :index
  end

  #form to create new blog
  def new
    @blog = Blog.new
    render :new
  end

  # creates new blog in db
  # that Belongs_to current_user
  def create
    blog = current_user.blog.create(blog_params)
    redirect_to blog_path(blog)
  end

  def show
    @blog = Blog.find(params[:id])
    render :show
  end

  def edit
    @blog = Blog.find(params[:id])
    if current_user.blog.include? @blog
      render :edit
    else
      redirect_to profile_path
    end
  end

  def update
    blog = Blog.find(params[:id])
    if current_user.blog.include? blog
      blog.update_attributes(blog_params)
      redirect_to blog_path(blog)
    else
      redirect_to profile_path
    end
  end 

  def destroy
    @blog = Blog.find(params[:id])
    if current_user.blog.include? @blog
      @blog.destroy(@blog)
      redirect_to profile_path, :notice => "Sucessfully Deleted"
    else
      redirect_to root_path
    end
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content)
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #login form
  def new
    if current_user
      redirect_to profile_path
    else
      render :new
    end
  end

  #authenticate the user, set session, create
  def create
  	user = User.find_by_email(user_params[:email])
  	if user && user.authenticate(user_params[:password])
  		session[:user_id] = user.id
  		redirect_to profile_path
  	else
  		redirect_to login_path
  	end
  end

  #clear session (log out)
  def destroy
  	session[:user_id] = nil
  	redirect_to root_path
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #form to create user
  def new
    if current_user
      redirect_to profile_path
    else
  	  @user = User.new
  	  render :new
    end

  end

  #creates new user in db
  def create
  	user = User.new(user_params)
  	if user.save
  		session[:user_id] = user.id
  		#redirect_to '/profile'
  		redirect_to profile_path
  	else
  		#redirect_to "/signup"
  		redirect_to signup_path
  	end

  end
  
  #show current_user
  def show
  	render :show
  end

  private
  	def user_params
  		params.require(:user).permit(:first_name, :last_name, :email, :password)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/blogs/_form.html.erb
_form.html.erb

app/views/blogs/create.html.erb
<h1>Blogs#create</h1>
<p>Find me in app/views/blogs/create.html.erb</p>

app/views/blogs/destroy.html.erb
<h1>Blogs#destroy</h1>
<p>Find me in app/views/blogs/destroy.html.erb</p>

app/views/blogs/edit.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <legend>Edit Blog</legend>
  <%= form_for @blog do |b| %>
    <%= b.label :title  %>:
     <%= b.text_field :title, class:"form-control" %><br />
     <%= b.label :content %>:
     <%= b.text_field :content, class:"form-control" %><br />
     <%= b.submit "Save Blog", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/blogs/index.html.erb
<div class='jumbotron'>
    <div class="container">
      <h1>Blog</h1>
      <% if current_user %> 
    		<p><%= current_user.email %></p> 
    		<p><%= link_to "Log Out",  logout_path, method: "delete", class: "btn btn-danger" %></p>
		<% else %> 
  			<p><%= link_to "Sign Up", signup_path , class: "btn btn-primary" %></p>
			<p><%= link_to "Log In", login_path , class: "btn btn-primary" %></p>
		<% end %> 
    </div>
 </div>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
    	<br>
     	<% if current_user %>
	    <%= link_to "Add New Blog", new_blog_path, class:"btn btn-lg btn-primary" %>
	    <% end %>  
    
    <% @blogs.each do |b| %>
      <div class="well col-xs-12">
        <h5><%= b.title %> - <%= b.content %><br> <%= link_to "VIew Blog",  blog_path(b), class: "btn btn-info" %></h5> 
      </div>
    <% end %>
	</div>
  </div>
</div>


<!-- 

<% @blogs.each do |b| %> 
	<p> <%= b.title %> - <%= b.content %> <%= link_to "VIew Blog", blog_path(b) %> </p>
<% end %>

<% if current_user %>
	<hr>
	<%= link_to "Add New Blog", new_blog_path %>
<% end %>  -->

app/views/blogs/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <legend>New Blog</legend>
  <%= form_for @blog do |b| %>
    <%= b.label :title  %>:
     <%= b.text_field :title, class:"form-control" %><br />
     <%= b.label :content %>:
     <%= b.text_field :content, class:"form-control" %><br />
     <%= b.submit "Save Blog", class:"btn btn-primary" %>
  <% end %>
</div>


<!-- <h1>New Blog</h1>
<%= form_for @blog do |b| %>
	<%= b.text_field :title, placeholder: "Title" %><br>
	<%= b.text_field :content, placeholder: "Content" %><br><hr>
	<%= b.submit "Save Blog" %>
<% end %>  -->

app/views/blogs/show.html.erb
<div class="container">
  <div class="row">	
    <div class="col-sm-6 col-sm-offset-3">
    	<div class="well col-xs-12">
    		<h2><%= @blog.title %></h2>
			  <hr>
			  <h3><%= @blog.content %></h3>
			  <% if current_user && current_user.blog.include?(@blog) %>
     			<p> <%= link_to "Edit Blog", edit_blog_path(@blog), class: "btn btn-primary" %></p>
          <p> <%= link_to "Delete Blog", profile_path, method: :delete, class: "btn btn-danger" %></p>
			  <% end %>
       
      </div>
    </div>
  </div>
</div>

app/views/blogs/update.html.erb
<h1>Blogs#update</h1>
<p>Find me in app/views/blogs/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>

  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
	<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<!-- shared nav-bar -->
	<%= render "shared/navbar" %>
	<%= yield %>

</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default" id="nav">
    <div class="container-fluid">
      <div class="navbar-header">
        <header>
          <img src=<%= asset_path"logo.jpg" %> width="50px"/> 
        </header>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><a href="/">Home</a></li>
          <li><a href="/">Blogs</a></li>
          <li><a href="/blogs/new">Post Blog</a></li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<div class="col-sm-4 col-sm-offset-4">
  <legend>Sign Up</legend>
  <%= form_for @user do |f| %>
    <%= f.label :first_name %>:
     <%= f.text_field :first_name, class:"form-control" %><br />
     <%= f.label :last_name %>:
     <%= f.text_field :last_name, class:"form-control" %><br />
     <%= f.label :email %>:
     <%= f.email_field :email, class:"form-control" %><br />
     <%= f.label :password %>:
     <%= f.password_field :password, class:"form-control" %><br />
     <%= f.submit "Sign Up", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='jumbotron'>
    <div class="container">
      <legend> Welcome to your Profile Page</legend>
      <% if current_user %> 
    		<h2><%= current_user.first_name %></h2> 
        <%= link_to "Add New Blog", new_blog_path, class:"btn btn-lg btn-primary" %>
    		<p><%= link_to "Log out",  logout_path, method: "delete", class: "btn btn-danger" %></p>
		<% else %> 
  			<p><%= link_to "Sign Up", signup_path , class: "btn btn-primary" %></p>
			<p><%= link_to "Log In", login_path , class: "btn btn-primary" %></p>
		<% end %> 
    </div>
 </div>

<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
    	<br>
     	  <% if current_user.blog.any? %>
     		<h3> My Blogs</h3>
     		<% current_user.blog.each do |b| %>
      			<div class="well col-xs-12">
        			<h5><%= b.title %> - <%= b.content %></h5>
              <p> <%= link_to "VIew Blog",  blog_path(b), class: "btn btn-info" %> </p>
      			</div>
        <% end %>
      	<% else %>
      		<h4>You don't have any blog! </h4>
	    	<%= link_to "Add New Blog", new_blog_path, class:"btn btn-primary" %>
	    <% end %>  

    </div>
    
  </div>
</div>





<!-- 

<h1>Profile Page</h1>
<div>
	<p><%= current_user.first_name %></p>
	<p><%= current_user.last_name %></p>
	<p><%= current_user.email %></p>
</div>

<% if current_user.blog.any? %>
	<h3>My blogs</h3>
	<% current_user.blog.each do |b| %>
		<p><%= b.title %> - <%= b.content %></p>
	<% end %>
<% else %>
	<h4>You don't have any blog </h4>
	<%= link_to "Add Blog", new_blog_path %>
<% end %> -->